# Project: myChamber
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe -D__DEBUG__
CC       = gcc.exe -D__DEBUG__
WINDRES  = windres.exe
OBJ      = main.o CRC_other.o sqlOperation.o
LINKOBJ  = main.o CRC_other.o sqlOperation.o
LIBS     = -L"D:/Program Files (x86)/Dev-Cpp/MinGW64/lib" -L"D:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -L""""C:/Program Files/MySQL/MySQL Server 5.7/lib"""" -static-libgcc -L"C:/Program Files/MySQL/MySQL Server 5.7/lib" ../MinGW64/x86_64-w64-mingw32/lib/libws2_32.a -lwsock32 ../lib/libmySQL.a -lmysql -g3
INCS     = -I"D:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"D:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Program Files/MySQL/MySQL Server 5.7/include"
CXXINCS  = -I"D:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"D:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"D:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++" -I""""C:/Program Files/MySQL/MySQL Server 5.7/include"""" -I"C:/Program Files/MySQL/MySQL Server 5.7/include"
BIN      = myChamber.exe
CXXFLAGS = $(CXXINCS) -g3
CFLAGS   = $(INCS) -g3
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

CRC_other.o: CRC_other.cpp
	$(CPP) -c CRC_other.cpp -o CRC_other.o $(CXXFLAGS)

sqlOperation.o: sqlOperation.cpp
	$(CPP) -c sqlOperation.cpp -o sqlOperation.o $(CXXFLAGS)
